export * from "@/svgs/Quit";
export * from "@/svgs/history";
export * from "@/svgs/Phone";
export * from "@/svgs/Email";
export * from "@/svgs/UserName";
export * from "@/svgs/Edit";
export * from "@/svgs/Logo";
export * from "@/svgs/Search";
export * from "@/svgs/UserSvg";
